language: python
python:
 - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install pytest-cov

script: 
  - pytest --with-coverage --cover-package=app

after_success:
  - coveralls

cache: pip3